Architectural_Engineering/urls.py
from django.contrib import admin
from django.urls import path, include
import accounts.views

urlpatterns = [
    path('', accounts.views.login),
    path('admin/', admin.site.urls),
    path('draw/', include('draw.urls')),
    path('manager/', include('manager.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    
]

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('', views.index, name="index"),
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('password/', views.password, name="password"),
    
    path('<str:username>/', views.profile, name="profile"),
]

draw/urls.py
# draw
# 신입생들이 동아리를 뽑기 위한 화면에 관련
from django.urls import path
from . import views
app_name = "draw"
urlpatterns = [
    path('', views.index, name="index"),
    path('choose_club', views.choose_club, name="choose_club"),
    path('select_finish', views.select_finish, name="select_finish"),
]

manager/urls.py
# draw
# 신입생들이 동아리를 뽑기 위한 화면에 관련
from django.urls import path
from . import views
app_name = "manager"
urlpatterns = [
    path('', views.index, name="index"),
    path('draw_result', views.draw_result, name="draw_result"),
]

manager/models.py
from django.db import models

# Create your models here.

manager/views.py
from django.shortcuts import render, redirect
from accounts.models import Profile
from draw.models import Draw
from django.contrib.auth.decorators import login_required
from .Club_Select_Algorithm import Club_Select_Algorithm
import csv
# Create your views here.

result = dict()

@login_required
def index(request):
    if request.user.is_staff:
        draw = Draw.objects.all()
        context = {
            'draw': draw,
        }

        return render(request, 'manager/index.html', context)
    else:
        return redirect('accounts:index')


def draw_result(request):
    draw = Draw.objects.all()
    
    csvfile = open(file="static/csv/result.csv",
                   mode="w", newline="", encoding="CP949")
    csvwriter = csv.writer(csvfile)
    csvwriter.writerow(['이름', '학번', '1지망', '2지망', '3지망'])
    for data in draw:
        data_to_list = [(data.user.user.username), (data.user.student_no),
                        (data.first), (data.second), (data.third)]
        csvwriter.writerow(data_to_list)
    csvfile.close()
    
    try:
        result = Club_Select_Algorithm().run(request.POST.get('i'))
        context = {
            'result': result,
        }
        return render(request, 'manager/result.html', context)
    except:
        return redirect('manager:index')

    

manager/templates/manager/index.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    {% block head %}
    {% endblock %}
</head>

<body class="bg-dark">
    <div class="container-fluid bg-dark">
        <ul class="nav justify-content-end">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'accounts:logout' %}">로그아웃</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'accounts:update' %}">개인정보 수정</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'accounts:login' %}">로그인</a>
            </li>
            {% endif%}
        </ul>
        <div class="row">
            <div class="col-xl-2"></div>
            <div class="col-xl-8">
                <table class="table-dark table-striped w-100">
                    <thead>
                        <th class="py-2">이름</th>
                        <th>학번</th>
                        <th>1지망</th>
                        <th>2지망</th>
                        <th>3지망</th>
                    </thead>
                    <tbody>
                        {% for data in draw %}
                        <tr>
                            <td>{{ data.user.user.username }}</td>
                            <td class="py-2">{{ data.user.student_no }}</td>
                            <td>{{ data.first }}</td>
                            <td>{{ data.second }}</td>
                            <td>{{ data.third }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <br>
                <form action="{% url 'manager:draw_result' %}" method="POST">
                    {% csrf_token %}
                    <span class="text-white">작업실 별 최소인원 : </span> <input type="number" name='i' class="form-number-input" value="0"></input>
                    <br>
                    <br>
                    <button class="btn btn-primary btn-block" type="submit"> 배정하기</button>
                </form>
            </div>
            <div class="col-xl-2"></div>
        </div>
        
        <div class="row py-5"></div>
    </div>
</body>

manager/templates/manager/result.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    {% block head %}
    {% endblock %}
</head>

<body class=" bg-dark">
    <div class="container-fluid bg-dark">
        <ul class="nav justify-content-end">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'accounts:logout' %}">로그아웃</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'accounts:update' %}">개인정보 수정</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'accounts:login' %}">로그인</a>
            </li>
            {% endif%}
        </ul>
        <div class="row mt-5">
            <div class="col-xl-1"></div>
            <div class="col-xl-3">
                <h1 class="text-white">작은공간</h1>
                <table class="table-dark table-striped w-100">
                    <thead>
                        <th class="py-2">학번</th>
                        <th>이름</th>
                    </thead>
                    <tbody>
                        {% for student_no,name in result.Small_Space.items %}
                        <tr>
                            <td class="py-2">{{ student_no }}</td>
                            <td>{{ name }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-xl-1"></div>
            <div class="col-xl-3">
                <h1 class="text-white">공간과 장소</h1>
                <table class="table-dark table-striped w-100">
                    <thead>
                        <th class="py-2">학번</th>
                        <th>이름</th>
                    </thead>
                    <tbody>
                        {% for student_no,name in result.Space_Place.items %}
                        <tr>
                            <td class="py-2">{{ student_no }}</td>
                            <td>{{ name }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-xl-1"></div>
            <div class="col-xl-3">
                <h1 class="text-white">뮤</h1>
                <table class="table-dark table-striped w-100">
                    <thead>
                        <th class="py-2">학번</th>
                        <th>이름</th>
                    </thead>
                    <tbody>
                        {% for student_no,name in result.Mu.items %}
                        <tr>
                            <td class="py-2">{{ student_no }}</td>
                            <td>{{ name }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-xl-3">
                <h1 class="text-white">소프</h1>
                <table class="table-dark table-striped w-100">
                    <thead>
                        <th class="py-2">학번</th>
                        <th>이름</th>
                    </thead>
                    <tbody>
                        {% for student_no,name in result.Sof.items %}
                        <tr>
                            <td class="py-2">{{ student_no }}</td>
                            <td>{{ name }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
             <div class="col-xl-3">
                <h1 class="text-white">아키</h1>
                <table class="table-dark table-striped w-100">
                    <thead>
                        <th class="py-2">학번</th>
                        <th>이름</th>
                    </thead>
                    <tbody>
                        {% for student_no,name in result.Arch.items %}
                        <tr>
                            <td class="py-2">{{ student_no }}</td>
                            <td>{{ name }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-xl-3">
                <h1 class="text-white">팀엑스</h1>
                <table class="table-dark table-striped w-100">
                    <thead>
                        <th class="py-2">학번</th>
                        <th>이름</th>
                    </thead>
                    <tbody>
                        {% for student_no,name in result.Team_X.items %}
                        <tr>
                            <td class="py-2">{{ student_no }}</td>
                            <td>{{ name }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-xl-3">
                <h1 class="text-white">비작업실</h1>
                <table class="table-dark table-striped w-100">
                    <thead>
                        <th class="py-2">학번</th>
                        <th>이름</th>
                    </thead>
                    <tbody>
                        {% for student_no,name in result.Nothing.items %}
                        <tr>
                            <td class="py-2">{{ student_no }}</td>
                            <td>{{ name }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row py-5"></div>
        
    </div>
</body>