Architectural_Engineering/urls.py
from django.contrib import admin
from django.urls import path, include
import accounts.views

urlpatterns = [
    path('', accounts.views.login),
    path('admin/', admin.site.urls),
    path('draw/', include('draw.urls')),
    path('manager/', include('manager.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    
]

draw/urls.py
# draw
# 신입생들이 동아리를 뽑기 위한 화면에 관련
from django.urls import path
from . import views
app_name = "draw"
urlpatterns = [
    path('', views.index, name="index"),
    path('choose_club', views.choose_club, name="choose_club"),
    path('select_finish', views.select_finish, name="select_finish"),
]

draw/models.py
from django.db import models
from accounts.models import Profile
from django.conf import settings
# Create your models here.

class Draw(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    first = models.CharField(max_length=50, blank=False)
    second = models.CharField(max_length=50, blank=False)
    third = models.CharField(max_length=50, blank=False)
    

draw/forms.py
from django import forms
from .models import Draw


DRAW_CHOICES = [
    ('팀엑스', '팀엑스'),
    ('공간과장소', '공간과장소'),
    ('뮤', '뮤'),
    ('소프', '소프'),
    ('아키', '아키'),
    ('작은공간', '작은공간'),
    ('비작업실', '비작업실')
]


class DrawForm(forms.ModelForm):
    class Meta:
        model = Draw
        fields = ['first', 'second', 'third']
        widgets = {
            'first': forms.RadioSelect(attrs={'class': 'form-check-inline text-white'}, choices=DRAW_CHOICES),
            'second': forms.RadioSelect(attrs={'class': 'form-check-inline text-white'}, choices=DRAW_CHOICES),
            'third': forms.RadioSelect(attrs={'class': 'form-check-inline text-white'}, choices=DRAW_CHOICES),
        }
        labels = {
            'first': '1지망',
            'second': '2지망',
            'third': '3지망',
        }

draw/views.py
from django.shortcuts import render, redirect
from accounts.models import Profile
from .forms import DrawForm
from .forms import Draw
from django.contrib.auth.decorators import login_required
# Create your views here.


@login_required
def index(request):
    user = request.user
    # 소셜로그인과 일반로그인 사이에서 발생하는 오류 처리를 위한 프로필생성
    if len(Profile.objects.filter(user=user)) == 0:
        Profile.objects.create(user=user)
        return redirect('accounts:update')

    # 이미 설문에 응답했을 경우 already=1
    already = 0
    if len(Draw.objects.filter(user=Profile.objects.get(user=user))):
        already = 1

    context = {
        "already": already,
        "name": user.username,
        "student_no": user.profile.student_no,
    }
    return render(request, 'draw/index.html', context)


@login_required
def choose_club(request):
    if request.method == "POST":
        print("POST")
        user = Profile.objects.get(user=request.user).user
        user.username = request.POST.get("id")
        user.save()
        name = user.username

        profile = Profile.objects.get(user=request.user)
        profile.student_no = request.POST.get("student_number")
        profile.save()
        student_no = profile.student_no
    else:
        print("GET")
        user = Profile.objects.get(user=request.user).user
        name = user.username
        profile = Profile.objects.get(user=request.user)
        student_no = profile.student_no
    form = DrawForm(instance=request.user.profile)
    context = {
        'form': form,
        'name': name,
        'student_no': student_no,
    }
    return render(request, 'draw/club.html', context)


@login_required
def select_finish(request):
    if request.method == 'POST':
        first = request.POST.get('first')
        second = request.POST.get('second')
        third = request.POST.get('third')
        if first != '비작업실':
            if first == second or first == third:
                return redirect('draw:choose_club')
        if second != '비작업실':
            if second == first or second == third:
                return redirect('draw:choose_club')
        if third != '비작업실':
            if third == first or third == second:
                return redirect('draw:choose_club')

        # 학생회장의 긴급요청으로 비작업실 중복선택 가능하게함
        # if first==second or second==third or first==third:

        user = Profile.objects.get(student_no=request.POST.get('student_no'))
        if len(Draw.objects.filter(user=user)) == 0:
            Draw.objects.create(user=user, first=request.POST.get(
                'first'), second=request.POST.get('second'), third=request.POST.get('third'))
        else:
            draw = Draw.objects.get(user=user)
            draw.first = request.POST.get('first')
            draw.second = request.POST.get('second')
            draw.third = request.POST.get('third')
            draw.save()
        context = {
            'first':first,
            'second':second,
            'third':third,
        }
    return render(request, 'draw/finish.html',context)

draw/templates/draw/club.html
{% extends 'base_accounts.html' %}
{% load bootstrap4 %}
<html>

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="/static/css/reset.css">
    <link rel="stylesheet" href="/static/css/main.css">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    {% block head %}
    <title>당신의 선택은?</title>
    <link rel="stylesheet" href="/static/css/reset.css">
    <link rel="stylesheet" href="/static/css/main.css">
    <style>
        .form-group > label {
            font-size: xx-large;
            margin-right: 10px;
            color: #fff;
        }
    </style>
    {% endblock %}
</head>

<body>
    {% block body %}
    <section class="choose-form w-50">
        <h1>당신의 선택은?</h1>
        <form action="{% url 'draw:select_finish' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="name" value={{name}} />
            <input type="hidden" name="student_no" value={{student_no}} />
            {% bootstrap_form form %}

            <div class="btn-area">
                <button class="button" type="submit"> 제출 </button>
            </div>
        </form>
    </section>
    {% endblock %}
</body>



</html>

draw/templates/draw/finish.html
{% extends 'base_accounts.html' %}

<html>

<head>
    <meta charset="utf-8">
    {% block head %}
    <title>당신의 선택은?</title>
    <link rel="stylesheet" href="/static/css/reset.css">
    <link rel="stylesheet" href="/static/css/main.css">
    {% endblock %}
</head>

<body>
    {% block body %}
    <section class="finish-form">
        <p>수고하셨습니다!!</p>
        <br>
        <p>결과를 기다려주세요</p>
        <br>

        <div class="text-left">
            <h3>1지망 : {{first}}</h3>
            <h3>2지망 : {{second}}</h3>
            <h3>3지망 : {{third}}</h3>
        </div>
    </section>
    {% endblock %}
</body>

</html>

draw/templates/draw/index.html
{% extends 'base_accounts.html' %}
<html>

<head>
    <meta charset="utf-8">
    {% block head %}
    <title>당신의 선택은?</title>
    <link rel="stylesheet" href="/static/css/reset.css">
    <link rel="stylesheet" href="/static/css/main.css">
    {% endblock %}
</head>

<body>
    {% block body %}
    <section class="login-form m-auto">
    <form action="{% url 'draw:choose_club' %}" method="post">
        {% csrf_token %}
            <h1>당신의 선택은?</h1>
            {% if already == 1 %}
            <p style="color: #FFFFFF;">이미 설문에 응답했습니다. 다시 제출하면 갱신됩니다. </p>
            {% endif %}
            <p style="color: #FFFFFF;">이름과 학번을 다시한번 꼼꼼하게 확인해주세요. </p>
            <div class="int-area">
                <input placeholder="이름" type="text" name="id" id="id" autocomplete="off" required value={{ name }}>
            </div>
            <div class="int-area">
                <input placeholder="학번" type="text" name="student_number" id="student_number" autocomplete="off"
                    required value={{ student_no }}>
            </div>
            <div class="btn-area">
                <button class="button" type="submit"> 제출 </button>
            </div>
        </form>
    </section>
    {% endblock %}
</body>

</html>