Architectural_Engineering/urls.py
from django.contrib import admin
from django.urls import path, include
import accounts.views

urlpatterns = [
    path('', accounts.views.login),
    path('admin/', admin.site.urls),
    path('draw/', include('draw.urls')),
    path('manager/', include('manager.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    
]

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('', views.index, name="index"),
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('password/', views.password, name="password"),
    
    path('<str:username>/', views.profile, name="profile"),
]

draw/urls.py
# draw
# 신입생들이 동아리를 뽑기 위한 화면에 관련
from django.urls import path
from . import views
app_name = "draw"
urlpatterns = [
    path('', views.index, name="index"),
    path('choose_club', views.choose_club, name="choose_club"),
    path('select_finish', views.select_finish, name="select_finish"),
]

accounts/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Profile(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	student_no = models.CharField(max_length=10, blank =False)
	""" 
	image = ProcessedImageField (
			blank = True,
    		upload_to = profile_image_path,
		 	processors = [ResizeToFill(300, 300)],
			format = 'JPEG',
			options = {'quality':90},
			)
	"""
	def __unicode__(self):
		return self.student_no+ " " + self.user.username

	def __str__(self):
		return self.student_no+ " " + self.user.username

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import get_user_model
from .models import Profile
from imagekit.forms import ProcessedImageField

class CustomUserChangeForm(UserChangeForm):
    password = None
    class Meta:
        model = get_user_model()
        fields = ['username', 'email']
        help_texts = {
            'username': '실명으로 입력하세요',
        }
        exclude = ['password']

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['student_no']
        widgets = {
            'student_no' : forms.TextInput(attrs={'class': 'form-control ','placeholder': '학번'}),
        }
        labels = {
            'student_no' : '학번',
        }
        help_texts = {
            'student_no': '틀리지않게 주의하세요',
        }
        
        

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from .forms import CustomUserChangeForm
from django.contrib.auth import update_session_auth_hash

from .models import Profile
from .forms import ProfileForm
from django.contrib.auth import get_user_model
from django.contrib import messages

import requests
import json
from django.db.models import Q

from allauth.socialaccount.adapter import DefaultSocialAccountAdapter
from allauth.account.views import SignupView

# Create your views here.

def index(request):
    return redirect('accounts:login')

def signup(request):
    if request.user.is_authenticated:
        return redirect('draw:index')
    else:
        if request.method == 'POST':
            form = UserCreationForm(request.POST)
            if form.is_valid():
                user = form.save()
                auth_login(request, user,
                           backend='django.contrib.auth.backends.ModelBackend')
                Profile.objects.create(user=user)
                messages.success(request, '회원가입 완료')
                return redirect('accounts:index')
            else:
                messages.error(request, '회원가입 실패')
        else:
            form = UserCreationForm()
        context = {
            'form': form
        }
    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('draw:index')
    else:
        if request.method == 'POST':
            form = AuthenticationForm(request, request.POST)
            if form.is_valid():
                auth_login(request, form.get_user())
                messages.success(request, '로그인 완료')
                return redirect(request.GET.get('next') or 'draw:index')
            else:
                messages.error(request, '로그인 실패')
        else:
            form = AuthenticationForm
        context = {
            'form': form
        }
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('accounts:index')

def profile(request, username):
    #회원 프로필보기 화면인데 현재 미구현
    context = {
    }
    return render(request, 'accounts/profile.html', context)



@login_required
def delete(request):
    request.user.delete()
    return redirect('accounts:index')

@login_required
def update(request):
    profile, created = Profile.objects.get_or_create(user=request.user)
    if profile:
        profile = request.user.profile
        if request.method == 'POST':
            form = CustomUserChangeForm(request.POST, instance=request.user)
            #p_form = PasswordChangeForm(request.user, request.POST)
            p_form = ProfileForm(request.POST, instance=profile)
            if form.is_valid() and p_form.is_valid():
                p = p_form.save(commit=False)
                p.student_no = request.POST.get('student_no')
                form.save()
                p.save()
                #user = p_form.save()
                #update_session_auth_hash(request, user)
                messages.success(request, '개인정보 수정 완료')
                return redirect('accounts:index')
            else:
                messages.success(request, '개인정보 수정 실패')
        else:
            
            form = CustomUserChangeForm(instance=request.user)
            p_form = ProfileForm(instance=request.user.profile)
            #p_form = PasswordChangeForm(request.user, request.POST)
    context = {
        'form': form,
        'p_form': p_form
    }
    return render(request, 'accounts/update.html', context)


@login_required
def password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, '비밀번호 변경 완료')
            return redirect('accounts:index')
        else:
            messages.success(request, '비밀번호 변경 실패')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/password.html', context)

accounts/templates/accounts/login.html
{% extends 'base_accounts.html' %}
{% load socialaccount %}
{% load bootstrap4 %}
{% load static %}
<head>
  <meta charset="utf-8">
  {% block head %}
  <link rel="stylesheet" href="/static/css/reset.css">
  <link rel="stylesheet" href="/static/css/main.css">
  {% endblock %}
</head>
{% block body %}

<div class="container-fluid">
  <div class="row mt-5 ">
    <a class="mx-auto" href="{% provider_login_url 'kakao' method='oauth2' %}"><img
      src="{%static 'img/kakao_login_large_wide.png'%}" /></a>
  </div>
</div>

{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base_accounts.html' %}
{% load bootstrap4 %}

{% block head %}
<script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
  integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
  integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
  integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
{% endblock%}

{% block body %}
<div class="">
  <div class="container">
    <div class="row p-5">
      <div class="col-xl-12">
        <h1>프로필 조회</h1>
      </div>
    </div>
    <div class="row p-3">
      <div class="col-xl-12">
        
      </div>
    </div>
  </div>
</div>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_accounts.html' %}
{% load bootstrap4 %}
{% block head %}
<script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
  integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
  integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
  integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

{% endblock %}
{% block body %}
<div class="container">
  <div class="row p-5">
    <div class="col-xl-12">
      <h1>회원가입</h1>
    </div>
    <div class="col-xl-12 mt-5">
      <form class="signup" id="signup_form" action="{% url 'accounts:signup' %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        {{ profile_form.as_p }}
        {% if redirect_field_value %}
        <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
        {% endif %}

        {% buttons %}
        <button type="submit" class="btn btn-primary " style="float:right; font-size: 20px;">
          가입완료
        </button>
        <a href="{% url 'accounts:index' %}" class="btn btn-primary  mr-3"
          style="float: right; font-size: 20px;">돌아가기</a>
        {% endbuttons %}
      </form>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/update.html
{% extends 'base_accounts.html' %}
{% load bootstrap4 %}
{% load static %}
{% block head %}
<script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
  integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
  integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
  integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<!-- summernote -->
<link href="{% static 'summernote-0.8.18-dist/summernote-bs4.min.css' %}" rel="stylesheet">
<script src="{% static 'summernote-0.8.18-dist/summernote-bs4.min.js' %}"></script>

<link rel="stylesheet" href="/static/css/reset.css">
<link rel="stylesheet" href="/static/css/main.css">
<style>
  label{
    color:#FFFFFF;
  }
</style>
{% endblock %}
{% block body %}
<div class="container">
  <div class="row p-5">
    <div class="col-xl-12">
      <h1 class="text-white">개인정보 수정</h1>
    </div>
    <div class="col-xl-3"></div>
    <div class="col-xl-6 mt-5">
      <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_form p_form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary " style="float:right; font-size: 20px;">
          수정완료
        </button>
        <a href="{% url 'accounts:index' %}" class="btn btn-primary  mr-3"
          style="float: right; font-size: 20px;">돌아가기</a>
        {% endbuttons %}
      </form>
    </div>
    <div class="col-xl-3"></div>
  </div>
</div>
{% endblock %}