Architectural_Engineering/urls.py
from django.contrib import admin
from django.urls import path, include
import accounts.views

urlpatterns = [
    path('', accounts.views.login),
    path('admin/', admin.site.urls),
    path('draw/', include('draw.urls')),
    path('manager/', include('manager.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    
]

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('', views.index, name="index"),
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('password/', views.password, name="password"),
    
    path('<str:username>/', views.profile, name="profile"),
]

draw/urls.py
# draw
# 신입생들이 동아리를 뽑기 위한 화면에 관련
from django.urls import path
from . import views
app_name = "draw"
urlpatterns = [
    path('', views.index, name="index"),
    path('choose_club', views.choose_club, name="choose_club"),
    path('select_finish', views.select_finish, name="select_finish"),
]

manager/urls.py
# draw
# 신입생들이 동아리를 뽑기 위한 화면에 관련
from django.urls import path
from . import views
app_name = "manager"
urlpatterns = [
    path('', views.index, name="index"),
    path('draw_result', views.draw_result, name="draw_result"),
]

Architectural_Engineering/templates/base_accounts.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <!-- Popper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

  {% block head %}
  {% endblock %}
</head>

<body>
  <div class="container-fluid">
    <section class="w-100">
      <ul class="nav justify-content-end">
        {% if user.is_authenticated %}
          {% if user.is_staff %}
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'manager:index' %}">관리자화면</a>
          </li>
          {% endif %}
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'accounts:logout' %}">로그아웃</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'accounts:update' %}">개인정보 수정</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'accounts:login' %}">로그인</a>
        </li>
        {% endif%}
      </ul>
    </section>
    <div class="row text-center">
      <div class="before w-100">
        <div class="body w-100">
          {% block body %}
          {% endblock %}
        </div>
      </div>
    </div>
  </div>
</body>

</html>